.Dd December 1, 2022
.Dt ZANE.TOWN 7
.Os "Zane Town"
.
.Sh NAME
.Nm Zane Schaffer
.Nd Human Person (he/him)
.
.Sh SYNOPSIS
.Nm email
.Mt personal.zane@gmail.com
.Nm
in
.Li #meta
on tilde.chat
.
.Sh DESCRIPTION
Former musician,
Future programmer,
Presently here.
.
.Pp
.Lk https://github.com/zschaffer code
\(em
.
.Pp

